namespace GloomChars.GameData.Models
{
    public enum CardAction
    {
        Miss,
        Damage, 
        MultiplyDamage,
        Disarm, 
        Stun, 
        Poison, 
        Wound, 
        Muddle, 
        AddTarget, 
        Immobilise, 
        Invisible, 
        Fire, 
        Ice, 
        Light, 
        Air, 
        Dark, 
        Earth, 
        Curse, 
        RefreshItem, 
        Push,
        Pull,
        Pierce,
        Heal,
        Shield
    }
}
